dataset: "AISHELL3"

val_size: 2

speaker_i: 7

text_cleaner: []

path:
    corpus_dir: "./corpus/data_aishell3"
    feature_dir: "./preprocessed_data/AISHELL3"



audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
mel:
    n_mel_channels: 80
    mel_fmin: 0.0
    mel_fmax: 8000.0 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
