batch_size: 2
group_size: 2

path:
  ckpt_dir: "./output/AISHELL3/ckpt"
  log_dir: "./output/AISHELL3/log"
  result_dir: "./output/AISHELL3/result"

optimizer:
  betas: [0.9, 0.999]
  eps: 0.00000001
  weight_decay: 0.0
  
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
  
  restore_step: 0
  
  grad_clip_thresh: 1.0
  
step:
  total_step: 9000
  log_step: 10
  val_step: 100
  save_step: 1000